// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwvdhpsxsnvsqifuslnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3dmRocHN4c252c3FpZnVzbG51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MjU5NzksImV4cCI6MjA3MTMwMTk3OX0.c71OWMbCSGKi0EpUyxv2y_geH8IaleU5oWIOl_9_Mlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});